### ISSUE TITLE
License

### ISSUE THREAD

**Issue by phicore** [i42output/neoGFX#135]
Quick question:

Will the engine/library be GPL 3 or only the editor/tools ?

Because I can see GPL 3 used for tools but not for a lib. 

GPL 3 imposes that the user can himself update the components
which are using this license. This is highly utopic. 

Can you imagine a game where the user should have the right to
update the engine and expect everything goes well?

Thanks

**Comment by i42output** [comment]
Hi. When version 1.0 of neoGFX is released next year there will be a dual licence: commercial and GPLv3.
