### ISSUE TITLE
[Feature Request] Xml based view-configuration

### ISSUE THREAD

**Issue by basisbit** [i42output/neoGFX#16]
First I want to say thanks for all your work and especially for publishing it all under GPLv3. You rock!
Did you ever consider implementing some theming support based on xml configuration files? SDL already is a good framework for game development. The neogfx project adds lots of UI components / framework, but as far as I know there is no "decent enough" game theming project out there. Maybe something XML based (a little bit like done in WPF) would be great! That would allow users / theme designers / modders to edit the look and feel of the applications UI, and software developers could focus more on the game logic, graphics effects, fixing bugs,... without having to care about horribly bad / legacy self-made theming systems to allow users to modify the location, size, partial transparency,... of user interface elements.

**Comment by FlibbleMr** [comment]
Hi! I plan on supporting CSS initially but perhaps something XML based too would be good; not really thought about it enough yet... :)

I also plan on adding scripting which could also do presentation separately to the C++ code.

**Comment by i42output** [comment]
UI description using FJSON is now available.
